name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check Mergeability
      id: check_mergeable
      run: |
        response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       -H "Accept: application/vnd.github+json" \
                       https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }})
        mergeable=$(echo "$response" | jq -r '.mergeable')
        if [[ "$mergeable" != "true" ]]; then
          echo "PR is not mergeable. Exiting."
          echo "mergeable=true" >> $GITHUB_ENV
          exit 1
        else
          echo "mergeable=false" >> $GITHUB_ENV
        fi
    

    - name: Check PR Title
      id: check_title
      run: |
        if [[ "${{ github.event.pull_request.title }}" == "autopull" ]]; then
          echo "match=true" >> $GITHUB_ENV
        else
          echo "match=false" >> $GITHUB_ENV
        fi

    - name: Merge Pull Request
      if: env.match == 'true'
      run: |
        curl -X PUT \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge

    - name: Delete branch after merge
      if: github.event.pull_request.merged == true
      run: |
        BRANCH_NAME=${{ github.event.pull_request.head.ref }}
        curl -X DELETE \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME"
