name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check PR Title
      id: check_title
      run: |
        if [[ "${{ github.event.pull_request.title }}" == "autopull" ]]; then
          echo "match=true" >> $GITHUB_ENV
        else
          echo "match=false" >> $GITHUB_ENV
        fi

    - name: Merge Pull Request
      if: env.match == 'true'
      run: |
        curl -X PUT \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge
